var bookdata = {
"1BWB-W+BW-WB+W-W+B-W-BB+W-WW-B+WBW-WBWBB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0WBW-WWB-BWW-WWB": {
"always": false,
"never": false,
"black": 4,
"white": 4,
"draw": 3,
},
"0BB-BBWB-WB-BWWB": {
"always": true,
"never": false,
"black": 8,
"white": 3,
"draw": 0,
},
"0WB-W-W+B-W-WW": {
"always": false,
"never": false,
"black": 487,
"white": 902,
"draw": 91,
},
"1WB-W-W+B-W-WW": {
"always": false,
"never": false,
"black": 487,
"white": 902,
"draw": 91,
},
"1BB-W+B-BBB-BB-BW+B-BB": {
"always": false,
"never": false,
"black": 6,
"white": 2,
"draw": 0,
},
"0BWW-B+W-B-WBW-B+W-B": {
"always": false,
"never": false,
"black": 2,
"white": 6,
"draw": 2,
},
"1BWW-B+W-B-WBW-B+W-B": {
"always": false,
"never": false,
"black": 2,
"white": 6,
"draw": 2,
},
"0WWBW-BW-WBBW-WW": {
"always": true,
"never": false,
"black": 8,
"white": 3,
"draw": 0,
},
"0WW-W-B+W-W-BW": {
"always": false,
"never": false,
"black": 271,
"white": 520,
"draw": 50,
},
"1BB-BB-B+W-BB-BB-B+W": {
"always": false,
"never": false,
"black": 6,
"white": 2,
"draw": 0,
},
"0BB-BB-B+W-BB-BB-B+W": {
"always": false,
"never": false,
"black": 6,
"white": 2,
"draw": 0,
},
"1B-BW+BB-W-B+W-W+BWB-BWW-W+B-WBB-WBB+WBW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0B-WW+B-BWB-WBWW-BW-W+B-B+WW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WBBW-WB-WBWW-WW": {
"always": true,
"never": false,
"black": 3,
"white": 2,
"draw": 0,
},
"0BBW-BWW-WBW-BWB": {
"always": false,
"never": false,
"black": 1,
"white": 6,
"draw": 0,
},
"1BBW-BWW-WBW-BWB": {
"always": false,
"never": false,
"black": 1,
"white": 6,
"draw": 0,
},
"1BWW-WBWB-WBW-WWBB": {
"always": false,
"never": false,
"black": 4,
"white": 1,
"draw": 1,
},
"1BWW-BBW-BBW-WWB": {
"always": false,
"never": false,
"black": 3,
"white": 3,
"draw": 0,
},
"1BWWB-B+W-W+B-W-BB+W-WB-W+BB-WWB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WBW-B-B+W-WW-WB": {
"always": false,
"never": false,
"black": 2,
"white": 3,
"draw": 0,
},
"0WB-W+B-WB-BWW-WWW": {
"always": false,
"never": false,
"black": 2,
"white": 3,
"draw": 0,
},
"0WBB-BBB-BW-B+W-BW": {
"always": false,
"never": false,
"black": 2,
"white": 3,
"draw": 0,
},
"1B-W+BB-BW-BB+W-B+W-W-B+W-W-B+WW-B+W": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WBWB-WBW-WWWB-BBW": {
"always": false,
"never": false,
"black": 1,
"white": 4,
"draw": 0,
},
"1WBWB-WB-BWWW-WW": {
"always": false,
"never": false,
"black": 3,
"white": 2,
"draw": 0,
},
"1WWB-BB-BB+W-WB-WB-B+W": {
"always": false,
"never": false,
"black": 3,
"white": 3,
"draw": 0,
},
"1W-W+B-WW-WB-WBB": {
"always": false,
"never": false,
"black": 4,
"white": 2,
"draw": 1,
},
"0WWW-W+BB-W-B+WB-B+W-BB-B+W-BWWB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WW-WBBW-BB-BBWW": {
"always": false,
"never": false,
"black": 4,
"white": 1,
"draw": 0,
},
"0WW-WBB-B+W-BB-BBW-W+B": {
"always": false,
"never": false,
"black": 2,
"white": 2,
"draw": 1,
},
"1WBB-BB-B+W-B-B+W-WB": {
"always": false,
"never": false,
"black": 8,
"white": 0,
"draw": 1,
},
"0BWBWB-WWB+W-W+B-W-BB+W-WW-B+WBW-WBWBB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0BBW-WBB-B+W-B-W+BW-W-B+WW": {
"always": true,
"never": false,
"black": 0,
"white": 2,
"draw": 0,
},
"0BBW-WWB-BWB-WBW": {
"always": false,
"never": false,
"black": 4,
"white": 1,
"draw": 0,
},
"0WBB-B+W-B-WWBB-WW": {
"always": false,
"never": false,
"black": 0,
"white": 4,
"draw": 1,
},
"1WWBW-B-BWWB-W": {
"always": false,
"never": true,
"black": 0,
"white": 4,
"draw": 0,
},
"0BB-BBW-BB-BBW": {
"always": false,
"never": false,
"black": 8,
"white": 3,
"draw": 0,
},
"1BB-BBW-BB-BBW": {
"always": false,
"never": false,
"black": 8,
"white": 3,
"draw": 0,
},
"0BWBW-BWBW-WBWW-WWWB": {
"always": false,
"never": false,
"black": 3,
"white": 3,
"draw": 4,
},
"1WW-WBB-BW-BWW": {
"always": false,
"never": false,
"black": 13,
"white": 2,
"draw": 1,
},
"0WWW-WWB-BW-B+W-BW": {
"always": false,
"never": true,
"black": 1,
"white": 4,
"draw": 0,
},
"1WBBW-WBWB-WBW-WB+W-WW": {
"always": false,
"never": false,
"black": 0,
"white": 6,
"draw": 1,
},
"1B-WWWW-WBBB-WB-BB+W-B+W": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1BBWWB-W-B+WW-WB-W+BB-BW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WWW-W+BB-W-B+WB-B+W-WW-B+W-BWWB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WB-WBW-B-W+B-BB": {
"always": false,
"never": false,
"black": 17,
"white": 5,
"draw": 1,
},
"0WB-WBWB-BB-WWBW": {
"always": false,
"never": false,
"black": 8,
"white": 0,
"draw": 1,
},
"1WB-WBWB-BB-WWBW": {
"always": false,
"never": false,
"black": 8,
"white": 0,
"draw": 1,
},
"1BWW-BB-WWB-BB": {
"always": true,
"never": false,
"black": 4,
"white": 0,
"draw": 0,
},
"0B-W+B-BBW-WBB-WW+B-W-WB+W": {
"always": true,
"never": false,
"black": 0,
"white": 7,
"draw": 0,
},
"1B-W+B-BBW-WBB-WW+B-W-WB+W": {
"always": true,
"never": false,
"black": 0,
"white": 7,
"draw": 0,
},
"1BB-W+B-BBB+W-WW-WB-W+BBW-BB-W+BBB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1B-WBB-BBW-WW-WW+B": {
"always": false,
"never": false,
"black": 5,
"white": 5,
"draw": 0,
},
"0WWB-B+W-W+B-W-BB+W-WB-W+B-WBW": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1W-BWW-WB-WB-B+W": {
"always": false,
"never": false,
"black": 21,
"white": 46,
"draw": 5,
},
"0WW-WB+W-WB-W+B-WWB-BBWB-B+W": {
"always": false,
"never": false,
"black": 9,
"white": 1,
"draw": 8,
},
"0BB-B+W-W-BWB-WB": {
"always": false,
"never": false,
"black": 50,
"white": 14,
"draw": 3,
},
"0BWW-WWB-BWW-WBW": {
"always": false,
"never": false,
"black": 3,
"white": 12,
"draw": 1,
},
"0BWBB-BWWWB-BWWW-B+WW-WB-WW+BB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0B-W+B-WB-B+W-B+W-W-B+W-W-B+WW-B+W": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0B-WW+BW-B-B+W-B+W-B-B+W-B-B+WBW": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0WBB-BBW-WBB-BWB": {
"always": false,
"never": false,
"black": 2,
"white": 4,
"draw": 0,
},
"0BWWB-W-W+BW-WWW-WWB": {
"always": false,
"never": false,
"black": 6,
"white": 1,
"draw": 0,
},
"1W-BW-WW-W-B+W": {
"always": false,
"never": false,
"black": 300,
"white": 494,
"draw": 49,
},
"0W-BW-WW-W-B+W": {
"always": false,
"never": false,
"black": 7,
"white": 12,
"draw": 2,
},
"0BW-WW+B-W-BWWB-BW-B+W": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0B-BW+BB-W-B+W-W+BW-WBB-BW-B+W-B+WBW": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0WW-WWBW-BW-WBBW": {
"always": true,
"never": false,
"black": 8,
"white": 2,
"draw": 0,
},
"0BWBBBW-BBW+B-B-W+B-BBB+W-B-BW+B-B+W-WBB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0WBWB-WBW-WBB-B+W-WW": {
"always": false,
"never": false,
"black": 3,
"white": 2,
"draw": 0,
},
"0BWW-B+W-BB-BW-B+W-B+W-B": {
"always": false,
"never": false,
"black": 3,
"white": 1,
"draw": 2,
},
"1BWW-B+W-BB-BW-B+W-B+W-B": {
"always": false,
"never": false,
"black": 3,
"white": 1,
"draw": 2,
},
"1BB-BB-B+W-B-BBW": {
"always": false,
"never": false,
"black": 24,
"white": 8,
"draw": 1,
},
"0BB-BB-B+W-B-BBW": {
"always": false,
"never": false,
"black": 24,
"white": 8,
"draw": 1,
},
"0WBB-BW+BW-WW-W+BW-B+W-WW-B+W-W+B-WBW-W+BW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0BW-W+BB-W-B+W-W+B-BWW-WBW-B+W": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0BWB-W+B-WB-BWW-W+B-BB": {
"always": false,
"never": false,
"black": 1,
"white": 3,
"draw": 1,
},
"1WWB-BB-BWW-BB": {
"always": true,
"never": false,
"black": 1,
"white": 0,
"draw": 0,
},
"1BB-W+B-B-W+B-BB-WWB": {
"always": false,
"never": false,
"black": 3,
"white": 4,
"draw": 1,
},
"1WBWW-WWW-WBWB-WBW": {
"always": false,
"never": false,
"black": 2,
"white": 5,
"draw": 10,
},
"0WW-BB-B+W-BB-BB-B+W": {
"always": false,
"never": false,
"black": 12,
"white": 9,
"draw": 2,
},
"0BB-BB+W-WB-WB-B+W-WWB": {
"always": false,
"never": false,
"black": 3,
"white": 3,
"draw": 0,
},
"0BWW-WBW+B-W-BB+W-WWW-BWWB-W+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0BWB-BB-BW+B-W-WWW": {
"always": false,
"never": false,
"black": 7,
"white": 5,
"draw": 2,
},
"1B-W+B-W+B-W-WBW-BWB": {
"always": false,
"never": false,
"black": 6,
"white": 0,
"draw": 2,
},
"1B-W+B-W+B-W-WBB-BBB": {
"always": false,
"never": false,
"black": 5,
"white": 3,
"draw": 7,
},
"0WBB-B-W+B-WW-WW": {
"always": false,
"never": false,
"black": 19,
"white": 17,
"draw": 4,
},
"0B-WBW-BW-WW-W+B": {
"always": false,
"never": false,
"black": 50,
"white": 14,
"draw": 3,
},
"0BW-BWB-BBBB-W-BB+WB": {
"always": false,
"never": false,
"black": 6,
"white": 0,
"draw": 0,
},
"1BWW-WWWB-BWW-BBWB": {
"always": false,
"never": false,
"black": 9,
"white": 3,
"draw": 0,
},
"1BWWB-W-WWBW-B": {
"always": false,
"never": true,
"black": 0,
"white": 5,
"draw": 1,
},
"0BB-W+B-BW-B+W-WW-BBWB": {
"always": false,
"never": false,
"black": 0,
"white": 1,
"draw": 5,
},
"1WBBB-BBW-WBWB-WBW": {
"always": false,
"never": false,
"black": 3,
"white": 1,
"draw": 1,
},
"1BBB-WB-WB-B+W-W": {
"always": false,
"never": false,
"black": 2,
"white": 6,
"draw": 1,
},
"0B-WWWW-WBB-BW-B+W-B+W": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0WBBW-WW-WWBW-BW": {
"always": true,
"never": false,
"black": 6,
"white": 0,
"draw": 1,
},
"0BB-BWBBW-WBWW-WWW-WB+WB": {
"always": false,
"never": false,
"black": 3,
"white": 0,
"draw": 5,
},
"0WWBWB-BB+W-WW-BB+WW-WW-BW+BW-BWBW": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0BWBBB-WBB-BBB-B+WB-BW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1WW-WWW-BWB-WB-B+W": {
"always": false,
"never": false,
"black": 2,
"white": 3,
"draw": 0,
},
"1B-W+B-BB-BBW-BW-B+W": {
"always": false,
"never": false,
"black": 7,
"white": 1,
"draw": 0,
},
"0B-W+B-BB-BBW-BW-B+W": {
"always": false,
"never": false,
"black": 7,
"white": 1,
"draw": 0,
},
"1WBW-BWB-WW-W+B-WW": {
"always": false,
"never": false,
"black": 2,
"white": 2,
"draw": 1,
},
"1BWW-W-B+WB-W-W+B-BB": {
"always": false,
"never": false,
"black": 5,
"white": 0,
"draw": 0,
},
"0BWW-BB-BW+B-W-WWB": {
"always": false,
"never": false,
"black": 5,
"white": 1,
"draw": 1,
},
"1WWWB-BWWWB-BBWB-BB+W-WB-W+B": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0BB-BBW-B-B+W-BB": {
"always": false,
"never": false,
"black": 141,
"white": 58,
"draw": 8,
},
"1WB-WB+W-WWBWW-BWWB-B+WW-W-B+WWBW-BB+W": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0BB-BB-B+WB-B-W+B-WB-B+W": {
"always": false,
"never": false,
"black": 5,
"white": 2,
"draw": 1,
},
"1BB-BB-B+WB-B-W+B-WB-B+W": {
"always": false,
"never": false,
"black": 5,
"white": 2,
"draw": 1,
},
"1BBB-B+W-W-B+W-WWW-WWB": {
"always": false,
"never": false,
"black": 1,
"white": 7,
"draw": 1,
},
"1WW-W+BB-W-B+W-W+BW-WB+W-BWB-BBWBW-WBW+B": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0BB-B+W-W-BWW-WW": {
"always": false,
"never": false,
"black": 9,
"white": 15,
"draw": 2,
},
"0WWB-WW+BWBB-BWW-BW+B-BBWB-B+W-WBWBB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1BB-WW+BW-B-B+W-B+W-B-B+W-BBWW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1WB-WB+W-B-B+WW-B-WW+B-BBW": {
"always": true,
"never": false,
"black": 0,
"white": 1,
"draw": 0,
},
"0WB-WB+W-B-B+WW-B-WW+B-BBW": {
"always": true,
"never": false,
"black": 0,
"white": 1,
"draw": 0,
},
"1BW-WW+B-W-BWWBB-WB-BB+W": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0B-W+B-W+B-B-WB+WW-B-WBW+B-B-W+B": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0W-W+B-W+B-BW-B+W-B-W+B-WW+B-W-W+B": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BB-BW-BB-WB": {
"always": false,
"never": false,
"black": 4,
"white": 1,
"draw": 0,
},
"1BB-BWB-WBW-WW-W+B": {
"always": false,
"never": false,
"black": 16,
"white": 6,
"draw": 2,
},
"0WWBB-BW+B-W-BB+W-WW-WB+W-WB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1WWB-BWB+W-W+B-W-BB+WB-B-WBW+BBW-BBW-B+W": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1BW-BW+B-WB-B-W+B-W+B-WB": {
"always": false,
"never": false,
"black": 9,
"white": 2,
"draw": 2,
},
"0BBBB-B-WB+W-BB-BB": {
"always": false,
"never": false,
"black": 2,
"white": 3,
"draw": 0,
},
"0BB-WWB-BB-WWB": {
"always": false,
"never": false,
"black": 7,
"white": 10,
"draw": 1,
},
"0BWB-WB-B+W-WW-WWW": {
"always": false,
"never": false,
"black": 2,
"white": 3,
"draw": 0,
},
"0BB-W+B-BW+B-W-BB+W-WWW-BWWB-W+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1WBBB-BBWB-BWBW-BWBW": {
"always": false,
"never": false,
"black": 7,
"white": 1,
"draw": 11,
},
"0BWWBW-WW+B-BB-BBBWW-B+W-BWW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1BW-BWBW-WW-W+B-W-B+WB": {
"always": false,
"never": false,
"black": 9,
"white": 6,
"draw": 1,
},
"0BBB-BBWBWW-BBWBB-BW+B-B+W-B-BBWB+WB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BWBB-BWWWB-BWWW-B+W-BW-W+BB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BBW-WW-WWB-WB": {
"always": false,
"never": false,
"black": 8,
"white": 1,
"draw": 0,
},
"1BB-WW+B-W-BBBWB-WB-BW+B": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BW-BWB-BBW-WW-W+B": {
"always": false,
"never": false,
"black": 19,
"white": 7,
"draw": 0,
},
"0WBB-WWB-B+W-BB-BBWW": {
"always": false,
"never": false,
"black": 7,
"white": 1,
"draw": 0,
},
"1BB-BBWW-WW-WBBW": {
"always": false,
"never": false,
"black": 4,
"white": 1,
"draw": 0,
},
"0WW-W+B-WB+W-WW-WB+WB-BBW-WB+W-WBW-B+W-W+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WW-W+BB-W-B+W-W+BWW-BWBWB-BBWBW-WBW+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WBBB-BB-B+WW-WBW-B+WW-WB-WW+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1BWW-WBBW-WBB-BWBB": {
"always": false,
"never": false,
"black": 5,
"white": 1,
"draw": 1,
},
"1WBW-WWBWB-BBW-BBWWB": {
"always": false,
"never": false,
"black": 4,
"white": 0,
"draw": 1,
},
"0WWWB-BWWWB-BBWB-BB+WW-BW-WW+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0BBB-B-W+B-W+B-W-WBB": {
"always": false,
"never": false,
"black": 5,
"white": 3,
"draw": 7,
},
"0BBWBB-WWBWBB-BBB-BW+BWBB-B-W+B-B+WB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0BW-WW-W+BBB-B+W-BB-BBB+W-B-BW+B-B+W": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0WB-WB-B+W-W-BWW": {
"always": false,
"never": false,
"black": 21,
"white": 46,
"draw": 5,
},
"1BB-B+W-WW-WBW-BWB": {
"always": false,
"never": false,
"black": 16,
"white": 6,
"draw": 2,
},
"1WB-W+B-W-W+B-WB-BBW": {
"always": false,
"never": false,
"black": 10,
"white": 8,
"draw": 2,
},
"0WW-WBBW-WB-WBWW": {
"always": true,
"never": false,
"black": 17,
"white": 1,
"draw": 1,
},
"0WB-WBB-W-W+B-WW": {
"always": false,
"never": false,
"black": 4,
"white": 2,
"draw": 1,
},
"0WWBW-BWB-B+WW-B-WW+B-B+W-WB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0BB-BW-B+WW-B-BBWB": {
"always": false,
"never": false,
"black": 3,
"white": 4,
"draw": 2,
},
"0BWBB-B+WB-WWB-BBWB+WW-BWW-BBWBW-W+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WBW-BWW-WWB-BWW": {
"always": false,
"never": false,
"black": 2,
"white": 4,
"draw": 0,
},
"0BWWB-W-B+WW-WB-W+B-WB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BWBBB-W-B+WW-BB-B+WB-BW": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BBBW-WWWW-B-W+B-W+BB-BW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0BB-WWW-BW-WWB": {
"always": false,
"never": false,
"black": 18,
"white": 35,
"draw": 3,
},
"1W-W+B-W+BB-WB-BB+W-B-W+B-WW+B-W-W+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0B-W+BBB-B+W-B-B+WBB-WBBBWB-BBW-W+B-B+WB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1WBB-BWWB-BWW-WBWW": {
"always": false,
"never": false,
"black": 5,
"white": 1,
"draw": 1,
},
"0W-WWB-BW-BW-W+B": {
"always": false,
"never": false,
"black": 89,
"white": 147,
"draw": 10,
},
"1WW-B+W-W+BW-WW-WB+W-WB+W-W-BBWB+W-W-B+W": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BW-WW-W+BBB-B+W-BB-BBB+W-BB-WBB+W": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0BWWBBB-BB-B+WW-WBWWB-WWBW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1W-BWW-WW-BB-B+W": {
"always": false,
"never": false,
"black": 9,
"white": 15,
"draw": 2,
},
"1WB-WB+W-W-BWB-BBW": {
"always": false,
"never": false,
"black": 2,
"white": 4,
"draw": 0,
},
"0WWBBB-BB-B+WW-WBWWB-WWB-W+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1W-WWB-BWB-WB-BW+B": {
"always": false,
"never": false,
"black": 1,
"white": 8,
"draw": 1,
},
"0B-B+WBB-BW+B-W-BB+W-WWW-BWWBW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1BB-BB-BBW-B-B+W": {
"always": false,
"never": false,
"black": 141,
"white": 58,
"draw": 8,
},
"0WW-WW+BB-WW-W+BB-BWBWW-WBWB-WB+WB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0BBB-BBW-WBBW-B-B+WB": {
"always": false,
"never": false,
"black": 6,
"white": 1,
"draw": 0,
},
"1BWBW-BWB-BWBB-BBB": {
"always": false,
"never": false,
"black": 2,
"white": 5,
"draw": 10,
},
"1WBBB-BB-B+WW-WBW-B+W-BW-W+B": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1WW-WBW-B+WB-B-WBWBW": {
"always": false,
"never": false,
"black": 4,
"white": 2,
"draw": 0,
},
"1BWBB-B+WB-WWB-BBWB+W-WW+B-W-BBWBW-W+B": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BB-BBB-WB-BBW": {
"always": false,
"never": false,
"black": 4,
"white": 1,
"draw": 0,
},
"0BB-BBB-WB-BBW": {
"always": false,
"never": false,
"black": 4,
"white": 1,
"draw": 0,
},
"1B-W+B-W+B-B-WB+WW-BB-WWBB-W+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0W-B+W-W-BW-WW": {
"always": false,
"never": false,
"black": 300,
"white": 494,
"draw": 49,
},
"1WBW-WW+B-BB-BBBW-B+W-WB-W+B": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0BBW-BBWWB-WBW-WWBWB": {
"always": false,
"never": false,
"black": 4,
"white": 0,
"draw": 1,
},
"1WB-WBB-BW-BWB": {
"always": false,
"never": false,
"black": 3,
"white": 2,
"draw": 0,
},
"1B-WW+B-BB-BWBW-BW-WB+WW": {
"always": true,
"never": false,
"black": 0,
"white": 2,
"draw": 0,
},
"0BB-B+W-BB-BBW-BBB": {
"always": false,
"never": false,
"black": 10,
"white": 4,
"draw": 0,
},
"1BB-BBWW-WBB-BBB-B+W": {
"always": false,
"never": false,
"black": 20,
"white": 3,
"draw": 0,
},
"0BB-BBWW-WBB-BBB-B+W": {
"always": false,
"never": false,
"black": 20,
"white": 3,
"draw": 0,
},
"0BB-BWWB-BW-BWBB": {
"always": true,
"never": false,
"black": 17,
"white": 1,
"draw": 1,
},
"0BBW-WB+W-W+B-W-BB+WB-B-WBW+B-W+B-WB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0BB-BWBW-BWB-BWW-W+B": {
"always": false,
"never": false,
"black": 3,
"white": 2,
"draw": 0,
},
"1B-W+BB-WW-WB-W+B-WB": {
"always": false,
"never": false,
"black": 6,
"white": 2,
"draw": 0,
},
"0WWW-W+BB-W-B+WBW-WWB-B+W-BWWB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1BW-W+BB-W-B+W-W+B-BWWB-BWW-BB+W": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0BBB-B-W+BB-BW-BBB": {
"always": false,
"never": false,
"black": 2,
"white": 3,
"draw": 0,
},
"0BWBB-WWB-BWW-BB+W-B": {
"always": false,
"never": false,
"black": 6,
"white": 1,
"draw": 1,
},
"1BWBB-WWB-BWW-BB+W-B": {
"always": false,
"never": false,
"black": 6,
"white": 1,
"draw": 1,
},
"0WW-W+BB-W-B+WB-BBWW-BW-W+BW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1BB-BWW-BB-WWB": {
"always": true,
"never": false,
"black": 5,
"white": 4,
"draw": 1,
},
"0BW-B+W-WB-WBW-WBB": {
"always": false,
"never": false,
"black": 10,
"white": 15,
"draw": 0,
},
"0WB-WWW-WBB-WW-W+B": {
"always": false,
"never": false,
"black": 2,
"white": 5,
"draw": 0,
},
"0BBW-WWWW-B-W+B-W+B-WB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0WW-WB-W-W+B-W": {
"always": false,
"never": false,
"black": 267,
"white": 380,
"draw": 51,
},
"0BWBB-WW-W+B-W-W+BB-BB": {
"always": false,
"never": false,
"black": 3,
"white": 5,
"draw": 1,
},
"1BWBB-WW-W+B-W-W+BB-BB": {
"always": false,
"never": false,
"black": 3,
"white": 5,
"draw": 1,
},
"0WBW-WW+B-BB-BBBW-B+WW-BW-WW+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1B-W+B-WWB-B-W+B-WBW": {
"always": false,
"never": false,
"black": 0,
"white": 3,
"draw": 2,
},
"0BWW-WWB-WBW-WWB": {
"always": false,
"never": false,
"black": 4,
"white": 4,
"draw": 3,
},
"0BWBW-BWBW-WBBB-BBWB": {
"always": false,
"never": false,
"black": 7,
"white": 1,
"draw": 11,
},
"0BWWBW-WW+B-BB-BBBWWB-WBWW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0B-WW+B-B-W+BW-BW-WBB-B+WW": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0BB-BW+B-BB-BB-W+B-BBB": {
"always": false,
"never": false,
"black": 6,
"white": 2,
"draw": 0,
},
"0B-BBW-WBB-WW-WB+W": {
"always": false,
"never": false,
"black": 5,
"white": 1,
"draw": 1,
},
"0WWW-W+BB-W-B+WB-BBW+B-B-WBWWB": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1BB-BBB-B+W-BB-BB-B+WB": {
"always": false,
"never": false,
"black": 7,
"white": 3,
"draw": 1,
},
"0WW-W+B-BW+B-W-BB+W-WWW-BWWB-W+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"1W-B+WW-W+BWBB-BWW-BW+B-BBWB-B+W-WBWBB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BWWB-WWBWW-W+BW-BW-W+BB-WBWW+B-W-WW+B": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BWW-WWW-W+B-W-W+B-BWW": {
"always": false,
"never": false,
"black": 11,
"white": 7,
"draw": 1,
},
"0BB-W+B-BBB+W-WW-WB-W+B-B+WB-B-W+BBB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"0B-W+B-WB-WW-WWB": {
"always": false,
"never": false,
"black": 1,
"white": 5,
"draw": 1,
},
"0BBB-BBW-BBW-WWB": {
"always": false,
"never": false,
"black": 5,
"white": 3,
"draw": 0,
},
"1BW-BWW-WB-WBW": {
"always": false,
"never": false,
"black": 3,
"white": 2,
"draw": 0,
},
"1WBB-BB-BWW-WB": {
"always": false,
"never": false,
"black": 13,
"white": 2,
"draw": 1,
},
"1BBW-B-B+W-BB-BB": {
"always": false,
"never": false,
"black": 70,
"white": 30,
"draw": 6,
},
"1BBW-BBW-WWB-BBB": {
"always": false,
"never": false,
"black": 5,
"white": 3,
"draw": 0,
},
"1W-BWWB-B-WBWW": {
"always": false,
"never": false,
"black": 3,
"white": 3,
"draw": 0,
},
"0W-BWWB-B-WBWW": {
"always": false,
"never": false,
"black": 3,
"white": 3,
"draw": 0,
},
"1W-W+BW-W+BW-WW-WB+W-W+B-WW-W+B-W-W+BWBB": {
"always": false,
"never": true,
"black": 0,
"white": 0,
"draw": 0,
},
"1BW-B+W-BWB-BB-W+B-WWB": {
"always": false,
"never": false,
"black": 0,
"white": 2,
"draw": 3,
},
"0BBB-BBW-BBBWB-WB-BW+B": {
"always": true,
"never": false,
"black": 0,
"white": 0,
"draw": 0,
},
"0WW-W+B-W-B+WB-BW-BWBW": {
"always": false,
"never": false,
"black": 9,
"white": 6,
"draw": 1,
},
"1WWB-WB-BBW-WW": {
"always": false,
"never": false,
"black": 4,
"white": 3,
"draw": 1,
},
"1BW-BWW-WW-WBB": {
"always": false,
"never": false,
"black": 6,
"white": 6,
"draw": 0,
},
"0WB-WBWW-WW-WBBW": {
"always": true,
"never": false,
"black": 17,
"white": 4,
"draw": 0,
}
};